function PIVlab2 = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  PIVLAB2 = IMPORTFILE(FILENAME) reads data from text file FILENAME for
%  the default selection.  Returns the numeric data.
%
%  PIVLAB2 = IMPORTFILE(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  PIVlab2 = importfile("C:\Users\user\Desktop\openpiv-podbox-master\openpiv-podbox-master\Matlab\PIVlab2.txt", [4, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 20-Jan-2021 10:30:16

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [4, Inf];
end

%% Setup the Import Options
opts = delimitedTextImportOptions("NumVariables", 4);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["xpx", "ypx", "upxframe", "vpxframe"];
opts.VariableTypes = ["double", "double", "double", "double"];
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
PIVlab2 = readtable(filename, opts);

%% Convert to output type
PIVlab2 = table2array(PIVlab2);
end